// This file is auto-generated by the i18n admin APIs.
// Do not edit manually. Use the admin language management UI.

export const locales: readonly string[] = ["en","tr"] as const;
export const defaultLocale: string = "en";

export default locales;
